# Generated by Django 5.1.4 on 2025-01-27 14:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_trading_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('balances', models.JSONField(default=list)),
                ('total_portfolio_value', models.DecimalField(decimal_places=0, help_text='총 포트폴리오 가치 (KRW)', max_digits=20)),
                ('krw_balance', models.DecimalField(decimal_places=0, help_text='KRW 잔액 (KRW)', max_digits=20)),
                ('total_coin_value', models.DecimalField(decimal_places=0, help_text='총 코인 가치 (KRW)', max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
