# Generated by Django 5.1.4 on 2025-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='krw_balance',
            field=models.PositiveBigIntegerField(help_text='KRW 잔액 (KRW)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_coin_value',
            field=models.PositiveBigIntegerField(help_text='총 코인 가치 (KRW)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_portfolio_value',
            field=models.PositiveBigIntegerField(help_text='총 포트폴리오 가치 (KRW)'),
        ),
    ]
