# Generated by Django 5.1.4 on 2025-02-04 01:57

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_portfolio_exchange_alter_portfolio_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpbitTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('coin', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, help_text='주문 금액 (KRW)', max_digits=20, null=True)),
                ('is_dca', models.BooleanField(default=False, help_text='DCA 여부')),
                ('uuid', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('paid_fee', models.DecimalField(blank=True, decimal_places=0, help_text='수수료 (KRW)', max_digits=20, null=True)),
                ('executed_volume', models.DecimalField(blank=True, decimal_places=8, help_text='체결된 수량', max_digits=17, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=8, help_text='체결된 평균 가격', max_digits=17, null=True)),
                ('order_detail', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
