# Generated by Django 5.1.4 on 2025-02-04 01:57

from django.db import migrations
from core import upbit
from core.utils import dict_pick
from django.utils.dateparse import parse_datetime


def migrate_upbit_trades(apps, schema_editor):
    UpbitTrading = apps.get_model("trading", "UpbitTrading")
    db_alias = schema_editor.connection.alias

    # 현재 잔고 데이터 조회
    data = upbit.get_balance_data()
    coins = {balance["symbol"].split(".")[0] for balance in data["balances"]}

    # 코인별로 최근 주문 내역 조회 및 저장
    tradings = []
    for coin in coins:
        # 최근 주문 내역 조회
        last_order = upbit.get_closed_orders(coin, count=1)[0]
        uuid = last_order["uuid"]
        order_detail = upbit.get_order_detail(uuid)

        # UpbitTrading 모델에 저장
        tradings.append(
            UpbitTrading(
                coin=coin,
                uuid=uuid,
                amount=order_detail["price"],
                state=order_detail["state"],
                order_detail=order_detail,
                average_price=order_detail.get("avg_buy_price"),
                created=parse_datetime(order_detail["created_at"]),
                **dict_pick(order_detail, "paid_fee", "executed_volume"),
            )
        )

    tradings.sort(key=lambda x: x.created)
    UpbitTrading.objects.using(db_alias).bulk_create(tradings)


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0016_upbittrading"),
    ]

    operations = [
        migrations.RunPython(migrate_upbit_trades, migrations.RunPython.noop),
    ]
