# Generated by Django 5.1.4 on 2025-05-26 16:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_auto_20250204_1057'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rsi_period', models.PositiveSmallIntegerField(default=14, help_text='RSI 계산에 사용되는 기간')),
                ('bollinger_period', models.PositiveSmallIntegerField(default=20, help_text='Bollinger 밴드 계산에 사용되는 기간')),
                ('bollinger_std', models.DecimalField(decimal_places=2, default=2.0, help_text='Bollinger 밴드 계산에 사용되는 표준편차 배수', max_digits=4)),
                ('buy_rsi_threshold', models.FloatField(default=30.0, help_text='매수 RSI 임계값')),
                ('sell_rsi_threshold', models.FloatField(default=70.0, help_text='매도 RSI 임계값')),
                ('buy_pressure_threshold', models.FloatField(default=0.6, help_text='매수 압력 기준')),
                ('sell_pressure_threshold', models.FloatField(default=0.4, help_text='매도 압력 기준')),
                ('stop_loss_pct', models.FloatField(default=0.02, help_text='손절 퍼센트')),
                ('take_profit_pct', models.FloatField(default=0.05, help_text='이익실현 퍼센트')),
                ('buy_profit_rate', models.FloatField(default=-5.0, help_text='매수 허용 최대 손실률')),
                ('sell_profit_rate', models.FloatField(default=5.0, help_text='매도 허용 최소 수익률')),
                ('max_krw_buy_ratio', models.FloatField(default=0.1, help_text='원화 매수 비율(최대)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
