# Generated by Django 5.1.4 on 2025-05-27 07:30

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_algorithmparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_processing', models.BooleanField(default=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('bollinger_upper', models.FloatField(blank=True, null=True)),
                ('bollinger_lower', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, max_length=10, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('btc_available', models.FloatField(blank=True, null=True)),
                ('krw_available', models.FloatField(blank=True, null=True)),
                ('trading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tradings', to='trading.trading')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
