# Generated by Django 5.1.4 on 2025-05-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_autotrading'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotrading',
            name='stop_loss_signal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
