# Generated by Django 5.1.4 on 2025-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_autotrading_btc_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotrading',
            name='btc_profit_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
