# Generated by Django 5.1.4 on 2025-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_autotrading_btc_profit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmparameter',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
