# Generated by Django 5.1.4 on 2025-06-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_autotrading_buy_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmparameter',
            name='add_buy_bollinger_band',
            field=models.FloatField(default=-1.5, help_text='추가 매수 허용 볼린저 하단 이탈 배수(σ)'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='add_buy_rsi_threshold',
            field=models.FloatField(default=20.0, help_text='추가 매수 허용 RSI 임계값'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='buy_chunk_ratio',
            field=models.FloatField(default=0.5, help_text='분할 매수 비율 (0~1)'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='max_additional_buys',
            field=models.PositiveSmallIntegerField(default=2, help_text='추가 매수(물타기) 최대 횟수'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='sell_chunk_ratio',
            field=models.FloatField(default=0.5, help_text='분할 매도 비율 (0~1)'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='stop_loss_cooldown_minutes',
            field=models.PositiveIntegerField(default=60, help_text='STOP LOSS 후 재진입 쿨타임(분)'),
        ),
    ]
