# Generated by Django 5.1.4 on 2025-08-31 06:52

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_algorithmparameter_add_buy_bollinger_band_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BybitSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('last_candle_time', models.DateTimeField()),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('macd_hist', models.FloatField(blank=True, null=True)),
                ('ema20', models.FloatField(blank=True, null=True)),
                ('ema50', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('volume_ma20', models.FloatField(blank=True, null=True)),
                ('atr', models.FloatField(blank=True, null=True)),
                ('buy_signal', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('expected_profit_pct', models.FloatField(blank=True, null=True)),
                ('decision', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'last_candle_time'], name='trading_byb_symbol_d394a1_idx')],
                'unique_together': {('symbol', 'timeframe', 'last_candle_time')},
            },
        ),
    ]
