# Generated by Django 5.1.4 on 2025-08-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_bybitsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltradingconfig',
            name='bybit_alert_enabled',
            field=models.BooleanField(default=False, help_text='Bybit 신호 텔레그램 알림 허용 여부'),
        ),
        migrations.AddField(
            model_name='historicaltradingconfig',
            name='bybit_target_coins',
            field=models.JSONField(blank=True, default=list, help_text="Bybit에서 스캔할 심볼 목록 (예: ['BTCUSDT','ETHUSDT'])", null=True),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='bybit_alert_enabled',
            field=models.BooleanField(default=False, help_text='Bybit 신호 텔레그램 알림 허용 여부'),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='bybit_target_coins',
            field=models.JSONField(blank=True, default=list, help_text="Bybit에서 스캔할 심볼 목록 (예: ['BTCUSDT','ETHUSDT'])", null=True),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='coinone_access_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='coinone_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='target_coins',
            field=models.JSONField(blank=True, default=list, help_text='List of target coins', null=True),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='coinone_access_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='coinone_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='target_coins',
            field=models.JSONField(blank=True, default=list, help_text='List of target coins', null=True),
        ),
    ]
