# Generated by Django 5.1.4 on 2025-09-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0027_historicaltradingconfig_bybit_alert_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bybitsignal',
            name='few_minutes_profitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bybitsignal',
            name='recommended_leverage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bybitsignal',
            name='side',
            field=models.CharField(blank=True, help_text='LONG or SHORT', max_length=10, null=True),
        ),
    ]
