# Generated by Django 5.1.4 on 2025-09-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_bybitsignal_few_minutes_profitable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bybitsignal',
            old_name='buy_signal',
            new_name='trade_signal',
        ),
    ]
