# Generated by Django 5.1.4 on 2026-04-02 09:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0029_rename_buy_signal_bybitsignal_trade_signal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BybitMechanicalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('review_lookback_hours', models.PositiveSmallIntegerField(choices=[(24, '24시간'), (72, '3일'), (168, '7일')], default=24, help_text='리뷰 시 조회할 과거 데이터 기간')),
                ('llm_reasoning', models.TextField(blank=True, help_text='LLM이 제안한 파라미터 변경 이유', null=True)),
                ('rsi_buy_threshold', models.FloatField(default=35.0, help_text='RSI 매수 임계값 (이하)')),
                ('rsi_sell_threshold', models.FloatField(default=65.0, help_text='RSI 매도 임계값 (이상)')),
                ('macd_min_histogram', models.FloatField(default=0.0, help_text='MACD 히스토그램 최소값')),
                ('adx_min_threshold', models.FloatField(default=20.0, help_text='ADX 최소값 (추세 강도)')),
                ('rsi_weight', models.FloatField(default=1.0, help_text='RSI 점수 가중치')),
                ('macd_weight', models.FloatField(default=1.0, help_text='MACD 점수 가중치')),
                ('ema_weight', models.FloatField(default=0.5, help_text='EMA 점수 가중치')),
                ('volume_weight', models.FloatField(default=0.5, help_text='Volume 점수 가중치')),
                ('min_score_for_entry', models.FloatField(default=5.0, help_text='진입에 필요한 최소 점수')),
                ('min_score_gap', models.FloatField(default=2.0, help_text='롱/숏 점수 차이 최소값')),
                ('stop_loss_pct', models.FloatField(default=0.02, help_text='손절 퍼센트 (2%)')),
                ('take_profit_pct', models.FloatField(default=0.04, help_text='익절 퍼센트 (4%)')),
                ('max_positions', models.PositiveSmallIntegerField(default=1, help_text='최대 동시 포지션 개수')),
                ('position_size_pct', models.FloatField(default=0.02, help_text='계좌 대비 포지션 크기 (2%)')),
                ('base_leverage', models.PositiveSmallIntegerField(default=2, help_text='기본 레버리지 (배)')),
                ('max_leverage', models.PositiveSmallIntegerField(default=3, help_text='최대 레버리지 (배)')),
                ('leverage_atr_multiplier', models.FloatField(default=1.0, help_text='ATR 기반 레버리지 조정 계수')),
                ('entry_cooldown_minutes', models.PositiveIntegerField(default=15, help_text='진입 후 재진입 쿨타임(분)')),
                ('daily_max_trades', models.PositiveSmallIntegerField(default=10, help_text='일일 최대 거래 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bybit Mechanical Parameter',
                'verbose_name_plural': 'Bybit Mechanical Parameters',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BybitMechanicalTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(default='BTCUSDT', max_length=20)),
                ('side', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('position_size_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('leverage', models.PositiveSmallIntegerField()),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('SIGNAL', 'Signal Reversal'), ('MANUAL', 'Manual Close')], max_length=20, null=True)),
                ('pnl_pct', models.FloatField(blank=True, help_text='수익률 (레버리지 포함)', null=True)),
                ('pnl_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entry_rsi', models.FloatField(blank=True, null=True)),
                ('entry_macd_hist', models.FloatField(blank=True, null=True)),
                ('entry_adx', models.FloatField(blank=True, null=True)),
                ('entry_score', models.FloatField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
