# Generated by Django 5.1.4 on 2026-04-02 12:39

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0030_bybitmechanicalparameter_bybitmechanicaltrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BybitMechanicalSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(default='BTCUSDT', max_length=20)),
                ('timeframe', models.CharField(default='5m', max_length=10)),
                ('candle_time', models.DateTimeField()),
                ('close_price', models.FloatField()),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_hist', models.FloatField(blank=True, null=True)),
                ('ema20', models.FloatField(blank=True, null=True)),
                ('ema50', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('volume_ma20', models.FloatField(blank=True, null=True)),
                ('atr', models.FloatField(blank=True, null=True)),
                ('adx', models.FloatField(blank=True, null=True)),
                ('score_long', models.FloatField(default=0)),
                ('score_short', models.FloatField(default=0)),
                ('action', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['symbol', 'candle_time'], name='trading_byb_symbol_54921f_idx')],
            },
        ),
    ]
