# Generated by Django 5.1.4 on 2026-04-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0031_bybitmechanicalsignal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bybitmechanicalparameter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bybitmechanicaltrade',
            name='user',
        ),
    ]
