# Generated by Django 5.1.4 on 2026-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_remove_bybitmechanicalparameter_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bybitmechanicalparameter',
            name='atr_avg_period',
            field=models.PositiveSmallIntegerField(default=20, help_text='ATR average period for breakout calculation'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalparameter',
            name='atr_breakout_ratio',
            field=models.FloatField(default=1.5, help_text='ATR breakout threshold (ATR must be this many times above its average)'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalparameter',
            name='bbands_period',
            field=models.PositiveSmallIntegerField(default=20, help_text='Bollinger Bands period'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalparameter',
            name='bbands_std',
            field=models.FloatField(default=2.0, help_text='Bollinger Bands standard deviation multiplier'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalparameter',
            name='min_conditions_for_entry',
            field=models.PositiveSmallIntegerField(default=3, help_text='Minimum number of conditions that must be met for entry (out of 5)'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalparameter',
            name='trailing_stop_activation_pct',
            field=models.FloatField(default=0.03, help_text='Activate trailing stop when profit reaches this percentage'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalparameter',
            name='trailing_stop_step_pct',
            field=models.FloatField(default=0.015, help_text='Trailing stop follows price by this percentage from peak'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalparameter',
            name='volume_spike_ratio',
            field=models.FloatField(default=1.5, help_text='Volume must be this many times above its moving average to confirm breakout'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalsignal',
            name='atr_avg',
            field=models.FloatField(blank=True, help_text='ATR average over atr_avg_period', null=True),
        ),
        migrations.AddField(
            model_name='bybitmechanicalsignal',
            name='bb_lower',
            field=models.FloatField(blank=True, help_text='Bollinger lower band', null=True),
        ),
        migrations.AddField(
            model_name='bybitmechanicalsignal',
            name='bb_position',
            field=models.FloatField(blank=True, help_text='Price position within BB (0=lower, 100=upper, 50=mid)', null=True),
        ),
        migrations.AddField(
            model_name='bybitmechanicalsignal',
            name='bb_upper',
            field=models.FloatField(blank=True, help_text='Bollinger upper band', null=True),
        ),
        migrations.AddField(
            model_name='bybitmechanicalsignal',
            name='conditions_met',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of entry conditions met (out of 5)'),
        ),
        migrations.AddField(
            model_name='bybitmechanicalsignal',
            name='volume_ratio',
            field=models.FloatField(blank=True, help_text='Volume / Volume MA', null=True),
        ),
        migrations.AddField(
            model_name='bybitmechanicaltrade',
            name='trailing_stop_activated',
            field=models.BooleanField(default=False, help_text='Whether trailing stop has been activated'),
        ),
        migrations.AddField(
            model_name='bybitmechanicaltrade',
            name='trailing_stop_price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Trailing stop price (updates as price moves in favor)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bybitmechanicalparameter',
            name='base_leverage',
            field=models.PositiveSmallIntegerField(default=5, help_text='기본 레버리지 (배)'),
        ),
        migrations.AlterField(
            model_name='bybitmechanicalparameter',
            name='max_leverage',
            field=models.PositiveSmallIntegerField(default=5, help_text='최대 레버리지 (배)'),
        ),
    ]
