# Generated by Django 5.1.4 on 2026-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_bybit_new_strategy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltradingconfig',
            name='max_trades_per_session',
            field=models.PositiveSmallIntegerField(default=2, help_text='한 세션에서 실행할 최대 거래 수 (품질 우선을 위해 제한)', verbose_name='세션당 최대 거래 수'),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='max_trades_per_session',
            field=models.PositiveSmallIntegerField(default=2, help_text='한 세션에서 실행할 최대 거래 수 (품질 우선을 위해 제한)', verbose_name='세션당 최대 거래 수'),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='min_coins',
            field=models.SmallIntegerField(default=0, help_text='한 번에 추천할 최소 코인 개수 (0은 거래 추천이 없을 수 있음)', verbose_name='최소 코인 개수'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='min_coins',
            field=models.SmallIntegerField(default=0, help_text='한 번에 추천할 최소 코인 개수 (0은 거래 추천이 없을 수 있음)', verbose_name='최소 코인 개수'),
        ),
    ]
